---
- name: Setup Zabbix
  hosts: slaves
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL server and client
      apt:
        name:
          - mysql-server
          - mysql-client
        state: present

    - name: Create Zabbix database and user
      mysql_db:
        name: zabbix
        state: present
        collation: UTF8_BIN
        encoding: UTF8
      become_user: root

    - name: Create Zabbix user
      mysql_user:
        name: 'zabbix'
        password: 'admin@123'
        priv: 'zabbix.*:ALL'
        host: '%'
        state: present
      become_user: root

    - name: Flush privileges
      mysql_db:
        name: zabbix
        state: flush_privs
      become_user: root

    - name: Create directory /downloads
      file:
        path: /downloads
        state: directory
        mode: 0755

    - name: Download Zabbix tarball
      get_url:
        url: https://ufpr.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/4.4.0/zabbix-4.4.0.tar.gz
        dest: /downloads/zabbix-4.4.0.tar.gz

    - name: Extract Zabbix tarball
      unarchive:
        src: /downloads/zabbix-4.4.0.tar.gz
        dest: /downloads
        remote_src: yes

    - name: Import Zabbix database schema
      mysql_db:
        name: zabbix
        state: import
        target: /downloads/zabbix-4.4.0/database/mysql/schema.sql
      become_user: zabbix

    - name: Import Zabbix database images
      mysql_db:
        name: zabbix
        state: import
        target: /downloads/zabbix-4.4.0/database/mysql/images.sql
      become_user: zabbix

    - name: Import Zabbix database data
      mysql_db:
        name: zabbix
        state: import
        target: /downloads/zabbix-4.4.0/database/mysql/data.sql
      become_user: zabbix
